### ISSUE TITLE
Does the plugin work with 3.2.3 ? 

### ISSUE THREAD

**Issue by anisc** [ChemicalInk/godot-arabic-text#10]
I'm having this error when i'm trying to enable the plugin with 3.2.3
Unable to load addon script from path: 'res://addons/arabic-text/ALabel_plugin.gd' There seems to be an error in the code, please check the syntax.
and sevral other error:
ALabel.gb : error (30,1): the method "wordwrap" isn't declared in the current class.
ALabel_plugin.gd : error (5,81)  Parse Error: Couldn't fully preload the script, possible cyclic reference or compilation error. Use "load()" instead if a cyclic reference is intended.

**Comment by anisc** [comment]
Had to add this **wrap_text** to ALabel.gd on line 31
`wordwrap.wrap_text(input, get_font("font"), get_rect().size)`
but now it doesn't seem to be working when using the translation server for godot

**Comment by 3akev** [comment]
Sorry for the late response. That's the cyclic reference fixed ... No idea how it got in there, I swear!
For the translation server, maybe another issue should be opened. I'll try to look into it, but know that I, ironically, haven't used it yet, so any details would be a great help.

Edit: Just saw #11, discussion can continue there.
